const STORAGE_KEY="imperio-medieval-save-v2";
const defaultState={playerName:"Senhor do Reino",castleLevel:1,resources:{madeira:900,comida:900,pedra:500,ferro:300,ouro:150},buildings:{castle:{level:1,cost:{madeira:250,pedra:120}},sawmill:{level:1,cost:{madeira:180}},farm:{level:1,cost:{madeira:160}},quarry:{level:1,cost:{madeira:220,pedra:80}},barracks:{level:1,cost:{madeira:260,pedra:100}},warehouse:{level:1,cost:{madeira:200,pedra:80}}},troops:{swordsman:20,archer:10,knight:0},log:["🏰 Seu reino foi fundado. O castelo aguarda seu comando."]};
function clone(o){return JSON.parse(JSON.stringify(o))}function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!saved)return clone(defaultState);return {...clone(defaultState),...saved,resources:{...defaultState.resources,...saved.resources},buildings:{...defaultState.buildings,...saved.buildings},troops:{...defaultState.troops,...saved.troops}}}catch{return clone(defaultState)}}
let state=loadState();
const buildingData={castle:["🏰","Castelo","Centro do reino. Aumenta seu nível.","castle"],sawmill:["🪵","Serraria","Produz madeira.","sawmill"],farm:["🌾","Fazenda","Produz comida.","farm"],quarry:["⛏️","Pedreira","Produz pedra.","quarry"],barracks:["⚔️","Quartel","Treina suas tropas.","barracks"],warehouse:["📦","Armazém","Protege e amplia recursos.","warehouse"]};
const troopData={swordsman:["🗡️","Espadachim","Infantaria equilibrada.",12,{comida:18,ferro:5}],archer:["🏹","Arqueiro","Ataque à distância.",10,{comida:16,madeira:4}],knight:["🐎","Cavaleiro","Unidade pesada.",25,{comida:30,ferro:12,ouro:4}]};
function fmt(n){return Math.floor(n).toLocaleString("pt-BR")}function toast(m){const e=document.getElementById("toast");e.textContent=m;e.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove("show"),1800)}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));toast("Progresso salvo!")}function silent(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}function canPay(c){return Object.entries(c).every(([k,v])=>(state.resources[k]||0)>=v)}function pay(c){Object.entries(c).forEach(([k,v])=>state.resources[k]-=v)}function costFor(k){const b=state.buildings[k],lv=b.level;return Object.fromEntries(Object.entries(b.cost).map(([x,v])=>[x,Math.floor(v*Math.pow(1.55,lv-1))]))}
function totalPower(){return state.troops.swordsman+state.troops.archer+state.troops.knight*3+state.castleLevel*10}
function renderResources(){const icons={madeira:"🪵",comida:"🌾",pedra:"🪨",ferro:"⛓️",ouro:"🪙"};document.getElementById("resources").innerHTML=Object.entries(state.resources).map(([k,v])=>`<div class="resource"><span>${icons[k]}</span><b>${fmt(v)}</b></div>`).join("")}
function renderBuildings(){document.getElementById("buildings").innerHTML=Object.entries(buildingData).map(([k,d])=>{const b=state.buildings[k],c=costFor(k),ok=canPay(c),txt=Object.entries(c).map(([x,v])=>`${x} ${fmt(v)}`).join(" • ");return `<article class="building"><div class="icon">${d[0]}</div><h3>${d[1]} <small>Lv.${b.level}</small></h3><p>${d[2]}<br>${txt}</p><button data-build="${k}" ${ok?"":"disabled"}>${k==="castle"?"EVOLUIR":"CONSTRUIR / EVOLUIR"}</button></article>`}).join("")}
function renderActivity(){document.getElementById("activityLog").innerHTML=state.log.map(x=>`<div>${x}</div>`).join("")}
function renderArmy(){document.getElementById("armyList").innerHTML=Object.entries(troopData).map(([k,d])=>{const c=d[4],ok=canPay(c);return `<article class="army-card"><div class="army-icon">${d[0]}</div><div><h3>${d[1]} × ${fmt(state.troops[k])}</h3><p>${d[2]} Poder ${d[3]} • ${Object.entries(c).map(([x,v])=>`${x} ${v}`).join(" • ")}</p></div><button data-troop="${k}" ${ok?"":"disabled"}>TREINAR</button></article>`}).join("");document.getElementById("playerPower").textContent=`Poder: ${fmt(totalPower())}`;document.getElementById("battlePower").textContent=`Poder: ${fmt(totalPower())}`;document.getElementById("quickPower").textContent=`${fmt(totalPower())} poder`}
function renderProfile(){document.getElementById("profileName").textContent=state.playerName;document.getElementById("profileLevel").textContent=state.castleLevel;document.getElementById("profilePower").textContent=fmt(totalPower());document.getElementById("profileTroops").textContent=fmt(Object.values(state.troops).reduce((a,b)=>a+b,0));document.getElementById("castleLevel").textContent=state.castleLevel;document.getElementById("playerName").textContent=state.playerName}
function render(){renderResources();renderBuildings();renderActivity();renderArmy();renderProfile()}
function showScreen(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.screen===id));render()}
function upgrade(k){const c=costFor(k);if(!canPay(c)){toast("Recursos insuficientes.");return}pay(c);state.buildings[k].level++;if(k==="castle")state.castleLevel=state.buildings[k].level;state.log.unshift(`🏗️ ${buildingData[k][1]} evoluiu para nível ${state.buildings[k].level}.`);state.log=state.log.slice(0,8);silent();render();toast(`${buildingData[k][1]} evoluído!`)}
function train(k){const d=troopData[k],c=d[4];if(!canPay(c)){toast("Recursos insuficientes.");return}pay(c);state.troops[k]++;state.log.unshift(`⚔️ ${d[1]} treinado.`);state.log=state.log.slice(0,8);silent();render();toast("Tropa treinada!")}
function battle(){const p=totalPower(),r=document.getElementById("battleResult");if(p<35){r.textContent="Você precisa de 35 de poder para iniciar a marcha.";return}const win=Math.random()<Math.min(.95,.45+p/200);if(win){const gold=80+Math.floor(Math.random()*71);state.resources.ouro+=gold;state.resources.comida+=50;r.textContent=`🏆 Vitória! +${gold} ouro e +50 comida.`;state.log.unshift(`🏆 Vitória contra a Guarnição Rebelde. +${gold} ouro.`)}else{r.textContent="🛡️ Ataque repelido. Reforce seu exército.";state.log.unshift("⚔️ A marcha foi repelida.")}state.log=state.log.slice(0,8);silent();render()}
document.addEventListener("click",e=>{const n=e.target.closest(".nav-item");if(n)showScreen(n.dataset.screen);const j=e.target.closest("[data-screen-jump]");if(j)showScreen(j.dataset.screenJump);const b=e.target.closest("[data-build]");if(b)upgrade(b.dataset.build);const t=e.target.closest("[data-troop]");if(t)train(t.dataset.troop);const p=e.target.closest("[data-place]");if(p)toast(`📍 ${p.dataset.place}`);if(e.target.closest("#saveBtn"))save();if(e.target.closest("#mailBtn"))toast("✉️ Nenhuma mensagem nova.");if(e.target.closest("#menuBtn"))toast("⚙️ Menu avançado em desenvolvimento.");if(e.target.closest("#attackBtn"))battle();if(e.target.closest("#resetBtn")&&confirm("Apagar o progresso e começar um novo reino?")){state=clone(defaultState);silent();render();toast("Novo reino criado!")}});
document.getElementById("enterBtn").addEventListener("click",()=>{document.getElementById("intro").classList.add("hidden");document.getElementById("app").classList.remove("hidden");sessionStorage.setItem("intro-seen","1")});
if(sessionStorage.getItem("intro-seen")){document.getElementById("intro").classList.add("hidden");document.getElementById("app").classList.remove("hidden")}
setInterval(()=>{state.resources.madeira+=state.buildings.sawmill.level*4;state.resources.comida+=state.buildings.farm.level*5;state.resources.pedra+=state.buildings.quarry.level*3;silent();render()},30000);render();
